(()=>{
const root=document.getElementById('app');
const DUNGEONS={
 ashen:{id:'ashen',name:'The Ashen Crypt',desc:'An old royal tomb where the dead refuse to sleep.',floors:7,boss:'Ashen Warden'},
 verdant:{id:'verdant',name:'Verdant Hollow',desc:'A living maze beneath strangled roots.',locked:true,coming:true},
 frost:{id:'frost',name:'The Frostvault',desc:'Something ancient waits below the ice.',locked:true,coming:true}
};
const CLASSES={
 warrior:{name:'Warrior',hp:30,damage:6,icon:'🛡️',passive:'Guarded: Defend blocks 7 damage.',ability:'Power Strike: 10 damage. 3-turn cooldown.'},
 rogue:{name:'Rogue',hp:22,damage:7,icon:'🗡️',passive:'Opportunist: +3 damage against wounded enemies.',ability:'Vanish: avoid the next enemy attack. 3-turn cooldown.'},
 ranger:{name:'Ranger',hp:24,damage:6,icon:'🏹',passive:'Hunter: first attack each combat deals +3.',ability:'Volley: 5 damage to every enemy. 3-turn cooldown.'},
 mage:{name:'Mage',hp:20,damage:8,icon:'🔮',passive:'Arcane Echo: every third basic attack deals +4.',ability:'Fireball: 12 damage. 3-turn cooldown.'}
};
const ENEMIES=[
 {name:'Crypt Rat',hp:8,atk:3,xp:1},{name:'Bone Thrall',hp:12,atk:4,xp:1},{name:'Grave Hound',hp:15,atk:5,xp:2},{name:'Hollow Knight',hp:19,atk:6,xp:2},{name:'Ash Acolyte',hp:17,atk:7,xp:2},{name:'Tomb Brute',hp:24,atk:7,xp:3}
];
const UPGRADES=[
 {id:'vigor',name:'Vitality',text:'+6 maximum HP and heal 6.',apply:s=>{s.maxHp+=6;s.hp=Math.min(s.maxHp,s.hp+6)}},
 {id:'edge',name:'Keen Edge',text:'+2 basic attack damage.',apply:s=>s.damage+=2},
 {id:'guard',name:'Iron Guard',text:'Defend blocks +3 damage.',apply:s=>s.guard+=3},
 {id:'blood',name:'Blood Drinker',text:'Heal 2 whenever you kill an enemy.',apply:s=>s.lifesteal+=2},
 {id:'quick',name:'Quick Hands',text:'Start each combat with 3 AP instead of 2.',apply:s=>s.bonusAP=1},
 {id:'focus',name:'Battle Focus',text:'Class ability cooldown reduced by 1.',apply:s=>s.cdReduce=Math.min(1,s.cdReduce+1)}
];
let state=null;
const saveMeta=()=>localStorage.setItem('delverMeta',JSON.stringify(meta));
let meta=(()=>{try{return JSON.parse(localStorage.getItem('delverMeta'))||{wins:0,losses:0,ashenCleared:false}}catch{return{wins:0,losses:0,ashenCleared:false}}})();
function shell(content){root.innerHTML=`<div class="app"><div class="top"><a class="back" href="../">‹ Games</a><div class="brand">DELVER</div><span></span></div>${content}</div>`}
function menu(){shell(`<section class="panel hero"><div class="kicker">SOLO DUNGEON ROGUELITE</div><h1>Delver</h1><p class="muted">Choose a class. Choose your path. Build a run. Kill the thing at the bottom.</p></section><div class="section-label">Choose Dungeon</div><section class="dungeons">${Object.values(DUNGEONS).map(d=>`<button class="dungeon ${d.locked?'locked':''}" data-d="${d.id}" ${d.locked?'disabled':''}><strong>${d.name}${d.coming?' · Coming Soon':''}</strong><span>${d.desc}</span>${d.id==='ashen'&&meta.ashenCleared?'<span class="loot">✓ Conquered</span>':''}</button>`).join('')}</section><section class="panel" style="margin-top:14px"><strong>Career</strong><p class="muted">Dungeon clears: ${meta.wins} &nbsp; • &nbsp; Fallen runs: ${meta.losses}</p></section>`);root.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>classSelect(b.dataset.d))}
function classSelect(did){const d=DUNGEONS[did];shell(`<h1 class="screen-title">${d.name}</h1><p class="muted">Choose who enters the dungeon.</p><div class="classes">${Object.entries(CLASSES).map(([id,c])=>`<button class="class-card" data-c="${id}"><strong>${c.icon} ${c.name}</strong><span>${c.hp} HP • ${c.damage} base damage</span><span class="ability">${c.passive}</span><span>${c.ability}</span></button>`).join('')}</div>`);root.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>start(did,b.dataset.c))}
function start(did,cid){const c=CLASSES[cid];state={dungeon:did,classId:cid,floor:0,hp:c.hp,maxHp:c.hp,damage:c.damage,guard:7,lifesteal:0,bonusAP:0,cdReduce:0,abilityCD:0,attackCount:0,upgrades:[],log:[],room:null,ap:2,block:0,avoid:false,firstAttack:true,finished:false};choosePath()}
function hud(){return `<div class="stats"><div class="stat"><span>HP</span><strong>${state.hp}/${state.maxHp}</strong></div><div class="stat"><span>AP</span><strong>${state.ap}</strong></div><div class="stat"><span>Damage</span><strong>${state.damage}</strong></div><div class="stat"><span>Floor</span><strong>${state.floor}/${DUNGEONS[state.dungeon].floors}</strong></div></div><div class="map">${Array.from({length:DUNGEONS[state.dungeon].floors},(_,i)=>`${i?'<i class="line"></i>':''}<span class="node ${i+1<state.floor?'done':i+1===state.floor?'current':''}">${i+1}</span>`).join('')}</div>${state.upgrades.length?`<div class="badges">${state.upgrades.map(x=>`<span class="badge">${x}</span>`).join('')}</div>`:''}`}
function choosePath(){state.floor++; if(state.floor===DUNGEONS[state.dungeon].floors){beginCombat(true);return} const types=pick(['combat','combat','treasure','camp','mystery'],3);shell(`${hud()}<section class="panel"><div class="kicker">THE PATH DIVIDES</div><h2>Choose your next room</h2><div class="choices">${types.map((t,i)=>roomChoice(t,i)).join('')}</div></section>`);root.querySelectorAll('[data-room]').forEach(b=>b.onclick=()=>enterRoom(b.dataset.room))}
function roomChoice(t,i){const m={combat:['⚔️','Battle','Fight enemies for an upgrade.'],treasure:['🗝️','Treasure','Claim a random permanent upgrade.'],camp:['🔥','Camp','Recover 35% of maximum HP.'],mystery:['❓','Unknown','Risk an uncertain encounter.']}[t];return `<button class="choice" data-room="${t}"><strong>${m[0]} ${m[1]}</strong><span>${m[2]}</span></button>`}
function enterRoom(t){if(t==='combat')beginCombat(false);else if(t==='treasure')offerUpgrades(3,()=>choosePath());else if(t==='camp'){const h=Math.ceil(state.maxHp*.35);state.hp=Math.min(state.maxHp,state.hp+h);messageRoom('🔥','A Quiet Fire',`You rest among the old stones and recover ${h} HP.`)}else mystery()}
function messageRoom(icon,title,text){shell(`${hud()}<section class="panel result"><div class="big">${icon}</div><h2>${title}</h2><p>${text}</p><button class="primary" id="continue">Descend</button></section>`);document.getElementById('continue').onclick=choosePath}
function mystery(){const r=Math.random();if(r<.4){const h=Math.ceil(state.maxHp*.25);state.hp=Math.min(state.maxHp,state.hp+h);messageRoom('⛲','Bloodless Fountain',`Cold water closes your wounds. Recover ${h} HP.`)}else if(r<.75){const dmg=4+Math.floor(Math.random()*5);state.hp-=dmg;if(state.hp<=0)return lose('A hidden trap ends your descent.');messageRoom('🪤','A Cruel Mechanism',`Ancient blades catch you. Lose ${dmg} HP.`)}else offerUpgrades(2,()=>choosePath())}
function makeEnemy(scale,boss=false){if(boss)return{name:'Ashen Warden',hp:52,maxHp:52,atk:9,boss:true};const base={...ENEMIES[Math.min(ENEMIES.length-1,Math.floor(Math.random()*(2+Math.ceil(scale/2))))]};base.hp+=Math.max(0,scale-2)*2;base.atk+=Math.floor(scale/3);base.maxHp=base.hp;return base}
function beginCombat(boss){const count=boss?1:(Math.random()<.45?2:1);state.room={type:'combat',boss,enemies:Array.from({length:count},()=>makeEnemy(state.floor,boss)),round:1};state.ap=2+state.bonusAP;state.block=0;state.avoid=false;state.firstAttack=true;state.log=[];renderCombat()}
function renderCombat(msg=''){const c=CLASSES[state.classId];const alive=state.room.enemies.filter(e=>e.hp>0);shell(`${hud()}${msg?`<div class="message">${msg}</div>`:''}<section class="panel"><div class="kicker">${state.room.boss?'BOSS':'COMBAT'} • ROUND ${state.room.round}</div>${alive.map((e,i)=>{const idx=state.room.enemies.indexOf(e);return `<div class="enemy"><div class="enemy-head"><h3>${e.boss?'👑 ':''}${e.name}</h3><strong>${e.hp}/${e.maxHp}</strong></div><div class="hpbar"><div class="hpfill" style="width:${Math.max(0,e.hp/e.maxHp*100)}%"></div></div><div class="combat-actions"><button data-attack="${idx}" ${state.ap<1?'disabled':''}>Attack</button><button data-ability="${idx}" ${state.ap<1||state.abilityCD>0?'disabled':''}>${c.ability.split(':')[0]}${state.abilityCD?` (${state.abilityCD})`:''}</button></div></div>`}).join('')}<div class="combat-actions"><button id="defend" ${state.ap<1?'disabled':''}>Defend</button><button class="primary" id="endTurn">End Turn</button></div></section><section class="panel log"><strong>Combat Log</strong>${state.log.slice(-6).reverse().map(x=>`<div>${x}</div>`).join('')}</section>`);root.querySelectorAll('[data-attack]').forEach(b=>b.onclick=()=>attack(+b.dataset.attack));root.querySelectorAll('[data-ability]').forEach(b=>b.onclick=()=>ability(+b.dataset.ability));document.getElementById('defend').onclick=defend;document.getElementById('endTurn').onclick=endTurn}
function attack(i){const e=state.room.enemies[i];if(!e||e.hp<=0||state.ap<1)return;let dmg=state.damage;if(state.classId==='warrior'){} if(state.classId==='rogue'&&e.hp<e.maxHp)dmg+=3;if(state.classId==='ranger'&&state.firstAttack)dmg+=3;if(state.classId==='mage'){state.attackCount++;if(state.attackCount%3===0)dmg+=4}state.firstAttack=false;e.hp-=dmg;state.ap--;state.log.push(`You hit ${e.name} for ${dmg}.`);killed(e);checkCombat()}
function ability(i){if(state.ap<1||state.abilityCD>0)return;const e=state.room.enemies[i];if(!e)return;const cd=3-state.cdReduce;if(state.classId==='warrior'){e.hp-=10;state.log.push(`Power Strike deals 10 to ${e.name}.`);killed(e)}else if(state.classId==='rogue'){state.avoid=true;state.log.push('You vanish into the dark.')}else if(state.classId==='ranger'){state.room.enemies.filter(x=>x.hp>0).forEach(x=>{x.hp-=5;killed(x)});state.log.push('Volley strikes every enemy for 5.')}else{e.hp-=12;state.log.push(`Fireball scorches ${e.name} for 12.`);killed(e)}state.abilityCD=cd;state.ap--;checkCombat()}
function defend(){if(state.ap<1)return;state.block+=state.guard;state.ap--;state.log.push(`You brace for ${state.guard} block.`);renderCombat()}
function killed(e){if(e.hp<=0&&!e.dead){e.dead=true;e.hp=0;state.log.push(`${e.name} falls.`);if(state.lifesteal){state.hp=Math.min(state.maxHp,state.hp+state.lifesteal);state.log.push(`Blood Drinker restores ${state.lifesteal} HP.`)}}}
function checkCombat(){if(state.room.enemies.every(e=>e.hp<=0)){if(state.room.boss)return win();return offerUpgrades(3,()=>choosePath())}renderCombat()}
function endTurn(){let total=0;for(const e of state.room.enemies.filter(x=>x.hp>0)){if(state.avoid){state.log.push(`You evade ${e.name}'s attack.`);state.avoid=false;continue}let dmg=e.atk;if(state.block){const blocked=Math.min(state.block,dmg);state.block-=blocked;dmg-=blocked}state.hp-=dmg;total+=dmg;state.log.push(`${e.name} hits for ${dmg}.`)}if(state.hp<=0)return lose('The dungeon claims another delver.');state.room.round++;state.ap=2+state.bonusAP;state.block=0;state.firstAttack=true;if(state.abilityCD>0)state.abilityCD--;renderCombat(total?`Enemies deal ${total} damage.`:'You weather the enemy assault.')}
function offerUpgrades(n,next){const opts=pick(UPGRADES,n);shell(`${hud()}<section class="panel"><div class="kicker">CHOOSE ONE</div><h2>Strength from the depths</h2><div class="upgrades">${opts.map((u,i)=>`<button class="upgrade" data-up="${i}"><strong>${u.name}</strong><span>${u.text}</span></button>`).join('')}</div></section>`);root.querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>{const u=opts[+b.dataset.up];u.apply(state);state.upgrades.push(u.name);next()})}
function win(){meta.wins++;meta.ashenCleared=true;saveMeta();endScreen(true,'The Ashen Warden breaks apart. The crypt is conquered — but deeper roads are beginning to open.')}
function lose(text){meta.losses++;saveMeta();endScreen(false,text)}
function endScreen(won,text){shell(`<section class="panel result"><div class="big">${won?'🏆':'☠️'}</div><div class="kicker">${won?'DUNGEON CONQUERED':'RUN ENDED'}</div><h2>${won?'Victory':'You Have Fallen'}</h2><p>${text}</p><p class="muted">${CLASSES[state.classId].name} • Reached floor ${state.floor} • ${state.upgrades.length} upgrades</p><button class="primary" id="again">Return to Dungeons</button></section>`);document.getElementById('again').onclick=menu}
function pick(arr,n){const a=[...arr];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a.slice(0,n)}
menu();
})();
